package com.fashion.mjysite.mapper;

import com.fashion.mjysite.entity.Atta;
import java.util.List;

public interface AttaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_atta
     *
     * @mbg.generated Tue Aug 28 12:18:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_atta
     *
     * @mbg.generated Tue Aug 28 12:18:49 CST 2018
     */
    int insert(Atta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_atta
     *
     * @mbg.generated Tue Aug 28 12:18:49 CST 2018
     */
    Atta selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_atta
     *
     * @mbg.generated Tue Aug 28 12:18:49 CST 2018
     */
    List<Atta> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_atta
     *
     * @mbg.generated Tue Aug 28 12:18:49 CST 2018
     */
    int updateByPrimaryKey(Atta record);
}