package com.fashion.mjysite.mapper;

import com.fashion.mjysite.entity.Atta;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface AttaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_atta
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_atta
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    int insert(Atta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_atta
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    Atta selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_atta
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    List<Atta> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_atta
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    int updateByPrimaryKey(Atta record);
}