package com.fashion.mjysite.mapper;

import com.fashion.mjysite.entity.Prform;
import java.util.List;

public interface PrformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_prform
     *
     * @mbg.generated Tue Aug 28 12:18:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_prform
     *
     * @mbg.generated Tue Aug 28 12:18:49 CST 2018
     */
    int insert(Prform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_prform
     *
     * @mbg.generated Tue Aug 28 12:18:49 CST 2018
     */
    Prform selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_prform
     *
     * @mbg.generated Tue Aug 28 12:18:49 CST 2018
     */
    List<Prform> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_prform
     *
     * @mbg.generated Tue Aug 28 12:18:49 CST 2018
     */
    int updateByPrimaryKey(Prform record);
}