package com.fashion.mjysite.mapper;

import com.fashion.mjysite.entity.Prform;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface PrformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_prform
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_prform
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    int insert(Prform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_prform
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    Prform selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_prform
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    List<Prform> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_prform
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    int updateByPrimaryKey(Prform record);
}