package com.fashion.mjysite.mapper;

import com.fashion.mjysite.entity.SignOrder;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SignOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sign_order
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sign_order
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    int insert(SignOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sign_order
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    SignOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sign_order
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    List<SignOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sign_order
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    int updateByPrimaryKey(SignOrder record);
}