package com.fashion.mjysite.entity;

import java.io.Serializable;

public class Article implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_article.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_article.articleid
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private Long articleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_article.article
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String article;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_article.id
     *
     * @return the value of sys_article.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_article.id
     *
     * @param id the value for sys_article.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_article.articleid
     *
     * @return the value of sys_article.articleid
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public Long getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_article.articleid
     *
     * @param articleid the value for sys_article.articleid
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setArticleid(Long articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_article.article
     *
     * @return the value of sys_article.article
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getArticle() {
        return article;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_article.article
     *
     * @param article the value for sys_article.article
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setArticle(String article) {
        this.article = article == null ? null : article.trim();
    }
}