package com.fashion.mjysite.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class FormDetail implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form_detail.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form_detail.formcode
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String formcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form_detail.partno
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private Integer partno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form_detail.description
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form_detail.quantity
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form_detail.unitprice
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private BigDecimal unitprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_form_detail.parttotal
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private BigDecimal parttotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form_detail.id
     *
     * @return the value of cost_form_detail.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form_detail.id
     *
     * @param id the value for cost_form_detail.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form_detail.formcode
     *
     * @return the value of cost_form_detail.formcode
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getFormcode() {
        return formcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form_detail.formcode
     *
     * @param formcode the value for cost_form_detail.formcode
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setFormcode(String formcode) {
        this.formcode = formcode == null ? null : formcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form_detail.partno
     *
     * @return the value of cost_form_detail.partno
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public Integer getPartno() {
        return partno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form_detail.partno
     *
     * @param partno the value for cost_form_detail.partno
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setPartno(Integer partno) {
        this.partno = partno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form_detail.description
     *
     * @return the value of cost_form_detail.description
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form_detail.description
     *
     * @param description the value for cost_form_detail.description
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form_detail.quantity
     *
     * @return the value of cost_form_detail.quantity
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form_detail.quantity
     *
     * @param quantity the value for cost_form_detail.quantity
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form_detail.unitprice
     *
     * @return the value of cost_form_detail.unitprice
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public BigDecimal getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form_detail.unitprice
     *
     * @param unitprice the value for cost_form_detail.unitprice
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setUnitprice(BigDecimal unitprice) {
        this.unitprice = unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_form_detail.parttotal
     *
     * @return the value of cost_form_detail.parttotal
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public BigDecimal getParttotal() {
        return parttotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_form_detail.parttotal
     *
     * @param parttotal the value for cost_form_detail.parttotal
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setParttotal(BigDecimal parttotal) {
        this.parttotal = parttotal;
    }
}