package com.fashion.mjysite.entity;

import java.io.Serializable;

public class MenuRole implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.menu_id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.role_id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.id
     *
     * @return the value of sys_menu_role.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.id
     *
     * @param id the value for sys_menu_role.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.menu_id
     *
     * @return the value of sys_menu_role.menu_id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.menu_id
     *
     * @param menuId the value for sys_menu_role.menu_id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.role_id
     *
     * @return the value of sys_menu_role.role_id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.role_id
     *
     * @param roleId the value for sys_menu_role.role_id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}