package com.fashion.mjysite.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Prform implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_prform.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_prform.formcdoe
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String formcdoe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_prform.formtype
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String formtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_prform.dept
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_prform.supplier
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_prform.delivery
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String delivery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_prform.originator
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String originator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_prform.totalprice
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private BigDecimal totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_prform.signflag
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String signflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_prform.flag
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_prform.creatdate
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    private Date creatdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_prform.id
     *
     * @return the value of cost_prform.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_prform.id
     *
     * @param id the value for cost_prform.id
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_prform.formcdoe
     *
     * @return the value of cost_prform.formcdoe
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getFormcdoe() {
        return formcdoe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_prform.formcdoe
     *
     * @param formcdoe the value for cost_prform.formcdoe
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setFormcdoe(String formcdoe) {
        this.formcdoe = formcdoe == null ? null : formcdoe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_prform.formtype
     *
     * @return the value of cost_prform.formtype
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getFormtype() {
        return formtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_prform.formtype
     *
     * @param formtype the value for cost_prform.formtype
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setFormtype(String formtype) {
        this.formtype = formtype == null ? null : formtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_prform.dept
     *
     * @return the value of cost_prform.dept
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_prform.dept
     *
     * @param dept the value for cost_prform.dept
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_prform.supplier
     *
     * @return the value of cost_prform.supplier
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_prform.supplier
     *
     * @param supplier the value for cost_prform.supplier
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_prform.delivery
     *
     * @return the value of cost_prform.delivery
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getDelivery() {
        return delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_prform.delivery
     *
     * @param delivery the value for cost_prform.delivery
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setDelivery(String delivery) {
        this.delivery = delivery == null ? null : delivery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_prform.originator
     *
     * @return the value of cost_prform.originator
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getOriginator() {
        return originator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_prform.originator
     *
     * @param originator the value for cost_prform.originator
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setOriginator(String originator) {
        this.originator = originator == null ? null : originator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_prform.totalprice
     *
     * @return the value of cost_prform.totalprice
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_prform.totalprice
     *
     * @param totalprice the value for cost_prform.totalprice
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_prform.signflag
     *
     * @return the value of cost_prform.signflag
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getSignflag() {
        return signflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_prform.signflag
     *
     * @param signflag the value for cost_prform.signflag
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setSignflag(String signflag) {
        this.signflag = signflag == null ? null : signflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_prform.flag
     *
     * @return the value of cost_prform.flag
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_prform.flag
     *
     * @param flag the value for cost_prform.flag
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_prform.creatdate
     *
     * @return the value of cost_prform.creatdate
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public Date getCreatdate() {
        return creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_prform.creatdate
     *
     * @param creatdate the value for cost_prform.creatdate
     *
     * @mbg.generated Wed Aug 29 11:55:59 CST 2018
     */
    public void setCreatdate(Date creatdate) {
        this.creatdate = creatdate;
    }
}